### ISSUE TITLE
Leaderboard Items

### ISSUE THREAD

**Issue by boozledorf** [IdleLands/GlobalBackend#3]
"Stamina Hogs"

- [x] Mastodon Phenomenon (Most Pet Phenomenon uses)
- [x] Grueling Dueling (Most Duel uses)
- [x] Enormous Performance (Most Orchestra uses)
- [x] Black Hat Fast Track (Most Hack The System uses)
- [x] Protection Projection (Most Cure Injury uses)
- [x] Ranked Unthanked (Most Experiencer uses)
- [x] General General (Most Generalize uses)
- [x] Best Jest in the West (Most Jest uses)
- [x] Alchemy Apogee (Most Alchemy uses)
- [x] Frustration Temptation (Most Tempt Fate uses)
- [x] Swap Shop (Most Swap Fiend uses)
- [x] Welcome to the Bone Zone (Most Bone Minions uses)
- [x] Villager Pillager (Most Pillage uses)
- [x] Fortune Foreman (Most Good Luck uses)
- [x] Yeast Beast of the East (Most Panhandle uses)

"The Best of the Best"

- [x] You're Still Here? (Most steps taken)
- [x] Quester Tester (Most quests completed)
- [x] Quester Bester (Most quest levels earned)
- [x] Shapeshifter (Most class changes)
- [x] Yo Mama (Norkos Dungeon -8: Lava Lake steps)
- [x] Reading is Fundamental (Most scrolls read)
- [x] First Among Equals (Most parties formed as Leader)

	
"The Best of the Rest"
- [x] Power Underwhelming (Most deaths)
- [x] I Put a Spell on You (Most Witch events)
- [x] Garbage Man's Lament (Most ForsakeItem events)
- [x] Can't See a Damn Thing (Most attacks missed)

Other stuff:
- [x] Yes Man (Most Affirmed decisions)
- [x] Naysayer (Most Denied decisions)
- [x] meh, whatever (Most Indecisive decisions)
- [x] Beam Me Up, Scotty (Most teleporters)
- [x] It's Getting Hot in Here (Most items unequipped)
- [x] Department of Redundancy Department (Most duplicate items found)

**Comment by DrKain** [comment]
All items from list added in 795470c2d92e6143ab93c52c38ae1d15fbc222ff, 05e6ef4c47568abb92590d1a2243705e9025dc31 and b7703abe19c7606e86a1cae63b4445ff2a6ea504
